name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        make install-ubuntu build 
        mkdir build

    - name: Run check
      run: make check
          
    - name: Upload Artifact GitHub Action
      uses: actions/upload-artifact@v3
      with: 
        name: snha*tar.gz
        path: build/

