name: Makefile CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup TeX Live
    - uses: teatimeguest/setup-texlive-action@v2
      with:
        packages: >-
            scheme-basic
            cleveref
            hyperref
          
    - uses: actions/checkout@v3
    - name: Build
      run: |
        make install-ubuntu 

    - name: Run check
      run: make check
          
    - name: Upload Artifact GitHub Action
      uses: actions/upload-artifact@v3
      with: 
        name: snha*tar.gz
        path: build/

