name: Makefile CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:       
    - uses: actions/checkout@v3
    - name: Build
      run: |
        sudo apt-get install texlive-base
        make install-ubuntu 
         
#    - name: Upload Artifact GitHub Action
#      uses: actions/upload-artifact@v3
#      with: 
#        name: snha*tar.gz
#        path: build/

