name: Makefile CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:       
    - uses: actions/checkout@v4
    - name: Build
      run: |
        sudo apt-get install texlive-base
        make install-ubuntu 
        mkdir build
        cp snha_0.2.1.tar.gz build/
    - name: Upload Artifact GitHub Action
      uses: actions/upload-artifact@v4
      with: 
         name: snha_0.1.0.tar.gz
         path: build/snha_0.2.1.tar.gz

